openapi: "3.0.0"

tags:
  name: health
  description: health Management API's

paths:
  /health:
    get:
      tags:
        - health

      responses:
        200:
          content:
            text/html; charset=utf-8:
              schema:
                type: string
                example: healthy
